auto: true
server: true

markdown: redcarpet

permalink: /:title/

exclude: ['CHANGELOG.md', 'README.md', 'LICENSE', 'Gruntfile.js', 'package.json', 'node_modules', 'sass', 'scripts'] # files to exclude