safe: true
auto: true
server: true

markdown: redcarpet

permalink: /:title/

include: ['.htaccess']
exclude: ['CHANGELOG.md', 'README.md', 'LICENSE', 'Gruntfile.js', 'package.json', 'node_modules']

# Site global text strings
lang:
  name: 'Jhaura Wachsman'
  tagline: 'Web Developer'
  email: 'jw@jhaurawachsman.com'
  domain: 'jhaurawachsman.com'
